console.log("======= step 1 =======");
var myFullName;
console.log("My Full Name is:",myFullName);
myFullName="Pratiksha Magdum";
console.log("After Initialization");
console.log("My Full Name:",myFullName);
myFullName="Pratiksha Sushant Magdum";
console.log("After Update The Name");
console.log("My Full Name:",myFullName);
console.log("======== step 2 ========");
var myLove;
myLove="I Love Only JS";
console.log(myLove);
console.log("======= step 3 ========");
var firstName="Pratiksha";
console.log("My FirstName:",firstName);
var lastName="Magdum";
console.log("My LastName:",lastName);
var age="22";
console.log("My Age:",age);
var address="Pune";
console.log("My Address:",address);
var pinCode="411023";
console.log("My PinCode Num:",pinCode);
var gender="Female";
console.log("My Gender:",gender);
var isMarried="YES";
console.log("Am I Married:",isMarried);